name: Publish npm package

on:
  release:
    types:
      - published

jobs:
  publish_to_registry:
    name: Publish npm package to npm and GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com
          scope: '@fastwebapp'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
